project:
  type: book
  output-dir: docs

number-sections: true
number-depth: 1
lightbox: true

book:
  title: "Digital Literacy"
  language: de
  author: "Nicolas Meseth"
  date: today

  sidebar:
    style: "floating"
    collapse-level: 1
  
  chapters:
    - index.qmd
    #- motivation.qmd

    - part: parts/part_1_representation.qmd
      chapters:
        - chapters/representation/problem_solving.qmd
        - chapters/representation/information.qmd
        - chapters/representation/counting.qmd
        - chapters/representation/bits.qmd
        - chapters/representation/codes.qmd
        
    
    - part: parts/part_2_processing.qmd
      chapters:
        - chapters/processing/algorithms.qmd
        - chapters/processing/computers.qmd
        - chapters/processing/arithmetic.qmd
        - chapters/processing/memory.qmd
        - chapters/processing/analog_digital.qmd

    - part: parts/part_2_programming.qmd
      chapters:
        
        - chapters/programming/variables.qmd
        - chapters/programming/control_structures.qmd
        - chapters/programming/loops.qmd
        - chapters/programming/functions.qmd
        - chapters/programming/reusability.qmd
    
    - part: parts/part_3_ai.qmd
      chapters:
        
        - chapters/ai/learning_but_rules.qmd
        - chapters/ai/supervised_learning.qmd
        - chapters/ai/unsupervised_learning.qmd
        - chapters/ai/neural_networks.qmd
        - chapters/ai/explainability.qmd
        
    - part: parts/part_4_daten.qmd
      chapters:
        
        - chapters/data/programming_with_r.qmd
        - chapters/data/data_analysis_with_r.qmd
        - chapters/data/structured_data.qmd
        - chapters/data/load_data.qmd
        - chapters/data/tidy_data.qmd
        - chapters/data/transform_data.qmd
        - chapters/data/visualize_data.qmd
        - chapters/data/communicate_findings.qmd
    
    - chapters/references.qmd
    
  appendices:
    - chapters/appendix/which_programming_language.qmd
    
language:
    title-block-author-single: "Autor"
    title-block-published: "Veröffentlicht"
    toc-title-document: "Inhalt"
    search-matching-documents-text: "Suchtreffer"
    crossref-ch-prefix: "Kapitel"
    crossref-sec-prefix: "Abschnitt"
    crossref-exr-prefix: "Übungsaufgabe"
    crossref-fig-title: "Abbildung"
    crossref-apx-prefix: "Anhang"
    section-title-appendices: "Anhang"
    
crossref:
  custom:
    - kind: float
      reference-prefix: Video
      key: vid

bibliography: references.bib

format:
  html:
    theme: comso
    code-link: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual

