project:
  type: book
  output-dir: docs

number-sections: true
number-depth: 2

book:
  title: "Digitalisierung, Programmieren und Künstliche Intelligenz"
  lang: de
  author: "Nicolas Meseth"
  date: today
  chapters:
    - index.qmd
    #- motivation.qmd
    
    - part: part_1_digitization.qmd
      chapters:
        
        - chapters/problems.qmd
        - chapters/counting.qmd
        - chapters/bits.qmd
        - chapters/codes.qmd
        - chapters/analog_digital.qmd
        - chapters/algorithms.qmd
        - chapters/logic.qmd
        - chapters/arithmetic.qmd
        
    - part: part_2_programming.qmd
      chapters:
        
        - chapters/variables.qmd
        - chapters/control_structures.qmd
        - chapters/loops.qmd
    
    - part: part_3_ai.qmd
      chapters:
        
        - chapters/learning_but_rules.qmd
    
    
    - chapters/references.qmd
    - chapters/appendix.qmd
    
language:
    title-block-author-single: "Autor"
    title-block-published: "Veröffentlicht"
    toc-title-document: "Inhalt"
    search-matching-documents-text: "Suchtreffer"
    crossref-ch-prefix: "Kapitel"
    crossref-sec-prefix: "Abschnitt"
    crossref-exr-prefix: "Übungsaufgabe"
    crossref-fig-title: "Abbildung"

bibliography: references.bib

format:
  html:
    theme: cosmo
    
editor: visual

