project:
  type: book
  output-dir: docs

number-sections: true
number-depth: 2
lightbox: true

book:
  title: "Digital Literacy"
  language: de
  author: "Nicolas Meseth"
  date: today
  chapters:
    - index.qmd
    #- motivation.qmd

    - part: parts/part_1_representation.qmd
      chapters:
        - chapters/representation/problems.qmd
        - chapters/representation/information.qmd
        - chapters/representation/counting.qmd
        - chapters/representation/bits.qmd
        - chapters/representation/codes.qmd
        
    
    - part: parts/part_2_processing.qmd
      chapters:
        - chapters/processing/algorithms.qmd
        - chapters/processing/logic.qmd
        - chapters/processing/arithmetic.qmd
        - chapters/processing/analog_digital.qmd

    - part: parts/part_2_programming.qmd
      chapters:
        
        - chapters/programming/variables.qmd
        - chapters/programming/control_structures.qmd
        - chapters/programming/loops.qmd
    
    - part: parts/part_3_ai.qmd
      chapters:
        
        - chapters/ai/learning_but_rules.qmd
        - chapters/ai/supervised_learning.qmd
        - chapters/ai/neural_networks.qmd
        
    - part: parts/part_4_daten.qmd
      chapters:
        
        - chapters/data/programming_with_r.qmd
        - chapters/data/data_analysis_with_r.qmd
        - chapters/data/vectors.qmd
        - chapters/data/data_frames.qmd
        - chapters/data/load_data.qmd
        - chapters/data/tidy_data.qmd
        - chapters/data/transform_data.qmd
        - chapters/data/visualize_data.qmd
        - chapters/data/communicate_findings.qmd
    
    - chapters/references.qmd
    - chapters/appendix.qmd
    
language:
    title-block-author-single: "Autor"
    title-block-published: "Veröffentlicht"
    toc-title-document: "Inhalt"
    search-matching-documents-text: "Suchtreffer"
    crossref-ch-prefix: "Kapitel"
    crossref-sec-prefix: "Abschnitt"
    crossref-exr-prefix: "Übungsaufgabe"
    crossref-fig-title: "Abbildung"
    
crossref:
  custom:
    - kind: float
      reference-prefix: Video
      key: vid

bibliography: references.bib

format:
  html:
    theme: comso
    
editor: visual

